name: Catch2 Tests Deploy Action

on: [push, pull_request, workflow_dispatch]

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout Catch2
        run: git clone https://github.com/catchorg/Catch2.git

      - name: Compile Catch2 tests
        run: mkdir build && cd build && cmake .. && make
        
      - name: Run Catch2 tests
        run: ./build/tests * --colour-mode win32