name: Doxygen GitHub Pages Deploy Action

on: [push, pull_request, workflow_dispatch]

jobs:
  deploy:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Doxygen Awesome CSS submodule
        run: git submodule add https://github.com/jothepro/doxygen-awesome-css.git -f